### ISSUE TITLE
More examples if possible

### ISSUE THREAD

**Issue by luistrigueiros** [fkorotkov/k8s-kotlin-dsl#23]
Hi just to say a big thanks for this repo it is very cool, and I have been exploring using it. I have found that maybe some examples maybe in the for of test per Kubernetes object type would be useful to start understanding how to use the builders.

Thank you. kindly
  Oscar

**Comment by fkorotkov** [comment]
Hey Oscar,

What kind of objects are you interested in? I'll add examples for you.

**Comment by luistrigueiros** [comment]
At the moment is Services, mainly. Thank you @fkorotkov .

**Comment by bjartek** [comment]
See here for an example on how to create a service https://github.com/Skatteetaten/boober/blob/e86f9a3120bb7a3852b4fff62c7aaee1be3eb709/src/main/kotlin/no/skatteetaten/aurora/boober/feature/AbstractDeployFeature.kt

**Comment by fkorotkov** [comment]
Added https://github.com/fkorotkov/k8s-kotlin-dsl/blob/master/example/src/main/kotlin/BaseService.kt

**Comment by luistrigueiros** [comment]
Many thanks  @fkorotkov
