### ISSUE TITLE
Fabric8 moved or dead?

### ISSUE THREAD

**Issue by kolloch** [fkorotkov/k8s-kotlin-dsl#28]
I noticed the the link in the README.md points to an "archived" repository: [fabric8 models](https://github.com/fabric8io/kubernetes-model)

```md
[fabric8 models](https://github.com/fabric8io/kubernetes-model)
```

I couldn't determine what the status of that dependency now is -- is it still maintained? What does it mean for this project?

Thank you.

**Comment by fkorotkov** [comment]
It got merged into the client repository. Updated the readme. Thanks for noticing!
