### ISSUE TITLE
Openshift variant

### ISSUE THREAD

**Issue by bjartek** [fkorotkov/k8s-kotlin-dsl#4]
Hello. 

We are looking into using this project but we are targetting Openshift. I see that you exclude those classes in a configuration settings. How do you want us to proceeed here? Can you create an artifact for oc-kotlin-dsl aswell as one for k8s-kotlin-dsl or should we just fork and create it ourselves?

We here is skatteetaten/tax norway IT.

**Comment by fkorotkov** [comment]
@bjartek, I'm very sorry to only notice this issue now. I was messing with my notification settings exactly around the time you created the issue and missed it.

I will check `openshift` support on the weekend. At first glance it doesn't seem to be as simple to add as kubernetes.

Sorry again for the late response.

**Comment by bjartek** [comment]
No problem.

I tried to build it locally with the filter on packages removed and it looked like it worked.

**Comment by bjartek** [comment]
Awesome!
